
import matplotlib.pyplot as plt

# Data points
technologies = [
    'Cloud Computing', 'Cybersecurity', 'Artificial Intelligence', 'IoT Devices', 
    'Blockchain', 'Quantum Computing', '5G Networks', 'AR/VR', 'Autonomous Vehicles', 
    'Edge Computing', 'Big Data Analytics', 'Wearable Technology', 'Robotics', 
    '3D Printing', 'Nanotechnology', 'Biotechnology', 'Smart Home', 'Drones', 
    'Space Tech', 'Fintech', 'Green Tech', 'Health Tech', 'Edu Tech', 'Legal Tech', 
    'Retail Tech', 'Ad Tech', 'Agritech', 'Insurtech', 'Proptech', 'Food Tech', 'HR Tech'
]
revenue = [
    11000, 9500, 8500, 7000, 6500, 6000, 5800, 5600, 5400, 5200, 5100, 5000, 4800, 4700, 
    4600, 4500, 4400, 4300, 4200, 4100, 4000, 3900, 3800, 3700, 3600, 3500, 3400, 3300, 
    3200, 3100, 3000
]

# Colors for each bar
colors = [
    '#FF5733', '#33FF57', '#3357FF', '#FF33A6', '#33FFA6', '#A633FF', '#FFA633', 
    '#33A6FF', '#FF5733', '#33FF57', '#3357FF', '#FF33A6', '#33FFA6', '#A633FF', 
    '#FFA633', '#33A6FF', '#FF5733', '#33FF57', '#3357FF', '#FF33A6', '#33FFA6', 
    '#A633FF', '#FFA633', '#33A6FF', '#FF5733', '#33FF57', '#3357FF', '#FF33A6', 
    '#33FFA6', '#A633FF', '#FFA633'
]

# Create a vertical bar chart
plt.figure(figsize=(14, 10))
plt.bar(technologies, revenue, color=colors, width=0.6)

# Modify the ticks, labels, and title
plt.ylabel('Revenue (in millions)')
plt.title('Revenue Generated by Various Technologies')
plt.xticks(rotation=90)
plt.ylim(2500, 12000)  # Adjusting the limit to start from 2500

# Display the plot
plt.tight_layout()
plt.show()