
import matplotlib.pyplot as plt

# Define the data points
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']
revenue_generated = [120, 140, 110, 160, 180, 150, 200, 140, 170, 130, 160, 110]

# Create the line chart
plt.figure(figsize=(14, 7))  # Changed width and height of the chart
plt.plot(months, revenue_generated, color='#2ca02c', marker='s')  # Changed color scheme and added markers

# Modify the trend by adjusting a data point
revenue_generated[6] = 200
plt.plot(months, revenue_generated, linestyle='-.', color='#d62728')  # Overlaying the modified trend line

# Assign annotation to the chart
for i, revenue in enumerate(revenue_generated):
    plt.annotate(f"{revenue}", (months[i], revenue_generated[i]), textcoords="offset points", xytext=(0,10), ha='center')

# Axes and title
plt.title('Monthly Revenue Generated by Startups in 2023')
plt.xlabel('Month')
plt.ylabel('Revenue ($k)')
plt.gca().invert_yaxis()  # Invert the y-axis
plt.grid(True)

# Display the plot
plt.show()